"""add characters.generation_method

Revision ID: d5ad9a9ee34b
Revises: 474a36a75db3
Create Date: 2026-07-20 20:53:32.638660

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5ad9a9ee34b"
down_revision: str | Sequence[str] | None = "474a36a75db3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default 是必须的：这张表在既有环境里已经有数据，加一个 NOT NULL
    # 列却不给默认值，数据库会直接拒绝执行这条迁移。
    #
    # 默认值取 "pointbuy" 而不是 "roll"：迁移之前建的卡都是走前端点数购买法
    # 做出来的（前端从未调用过 roll-attributes 端点），标成 pointbuy 才符合
    # 事实，也让它们继续受总预算校验约束。
    op.add_column(
        "characters",
        sa.Column(
            "generation_method",
            sa.String(length=20),
            nullable=False,
            server_default="pointbuy",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "generation_method")
    # ### end Alembic commands ###
